spring.application.name=MediStore User Management

# Server
server.port=8081

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# File Storage (users.txt path)
app.storage.users-file=data/users.txt

# App
app.name=MediStore
app.version=1.0.0
